blank_issues_enabled: false
contact_links:
  - name: Issues - Kubeflow Notebooks
    url: https://github.com/cgu-kubeflow/notebooks/issues
    about: Please use the `kubeflow/notebooks` repository

  - name: Issues - Kubeflow Pipelines
    url: https://github.com/cgu-kubeflow/pipelines/issues
    about: Please use the `kubeflow/pipelines` repository

  - name: Issues - Kubeflow Training Operator
    url: https://github.com/cgu-kubeflow/training-operator/issues
    about: Please use the `kubeflow/training-operator` repository

  - name: Issues - Kubeflow Platform - Central Dashboard
    url: https://github.com/cgu-kubeflow/dashboard/issues
    about: Please use the `kubeflow/dashboard` repository

  - name: Issues - Kubeflow Platform - Profile Controller
    url: https://github.com/cgu-kubeflow/dashboard/issues
    about: Please use the `kubeflow/dashboard` repository

  - name: Issues - Kubeflow Platform - Kubeflow Manifests
    url: https://github.com/cgu-kubeflow/manifests/issues
    about: Please use the `kubeflow/manifests` repository
