apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: {name}
  namespace: "{namespace}"
  labels:
    app: {name}
    isTemplateName: {isTemplate}
  annotations:
    notebooks.kubeflow.org/server-type: ""
    notebooks.kubeflow.org/creator: {creator}
    jsonStr: {jsonStr}
spec:
  template:
    spec:
      serviceAccountName: {serviceAccount}
      containers:
        - name: {name}
          image: ""
          volumeMounts: []
          env: []
          resources:
            requests:
              cpu: "0.1"
              memory: "0.1Gi"
          securityContext:
            capabilities:
              add:
              - IPC_LOCK    
      volumes: []
      tolerations: []


      
